#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-ZH-CEDICT
version:      0.04
version_from: lib/Lingua/ZH/CEDICT.pm
installdirs:  site
requires:
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
